routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){

    Auth::routes();
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/redirect_to_sa_panel', 'DashboardController@redirectToSaPanel');

    // Route::get('/applications', function () {
    //     return view('pages.applications.index');
    // });

    // Route::get('/applications/create', function () {
    //     return view('pages.applications.create');
    // });

    Route::resource('applications', 'ApplicationController');
    Route::get('/application_detail/{id}', 'ApplicationController@applicationDetail');

    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
    Route::post('/image-file-delete', 'PostController@imageFileDelete')->name('imageFileDelete');

    Route::resource('notifications', 'NotificationController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/notification-type', 'SettingsController@notificationTypeStore')->name('notificationTypeCreate');
    Route::put('/notification-type', 'SettingsController@notificationTypeUpdate')->name('notificationTypeUpdate');
    Route::delete('/notification-type/{id}', 'SettingsController@notificationTypeDelete')->name('notificationTypeDelete');

    Route::post('/server-key', 'SettingsController@serverKey')->name('serverKey');

    Route::get('/firebase','FirebaseController@index');
    // Route::resources([
    //     'applications' => 'ApplicationController'
    // ]);
});
  

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    //
}

app/NotificationType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NotificationType extends Model
{
    //
}

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

use App\Notification;
use App\NotificationType;
use Illuminate\Http\Request;
use File;
use App\Library\Services\FirebaseService;

class NotificationController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notifications = Notification::where('application_id',session()->get('application')['id'])->orderBy('id','DESC')->get();
        for($i=0; $i<count($notifications); $i++){
            $notifications[$i]->type_name = NotificationType::find($notifications[$i]->type_id)->name;
        }
        return view('admin.notifications.index')->with('notifications', $notifications);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $notificationTypes = NotificationType::where('application_id',session()->get('application')['id'])->orderBy('id','DESC')->get();
        return view('admin.notifications.create')->with('notificationTypes', $notificationTypes);;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store( Request $request, FirebaseService $firebaseService )
    {
        $niceNames = [
            'title' => 'Title',
            'type' => 'Type',
            'body' => 'Body',
            'img_name' => 'Image'
        ];
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'body' => 'required',
            'img_name' => 'image|mimes:jpg,jpeg,png,gif'
        ], [], $niceNames);

     
        //image
        $fileName = null;        
        if ($request->hasFile('img_name')) {
            $file = $request->file('img_name');
            $fileName = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
            $file->move('./uploads/notifications/', $fileName);
        }

        $notification = new Notification();
        $notification->title = $request->get('title');
        $notification->type_id = $request->get('type');
        $notification->body = $request->get('body') ;
        $notification->img_name = $fileName;
        $notification->application_id =  session()->get('application')['id'];
        $notification->created_by = Auth()->user()->id;

        if ($notification->save()) {

            $notificationType = NotificationType::find($notification->type_id);
            if($fileName)
                $filePath =  url('uploads/notifications/'.$fileName);
            else
                $filePath= "";
            $renResult = $firebaseService->pushNotifications($notification->title, $notificationType->name, $notification->body, $filePath );
            $request->session()->flash('alert-success', 'Notificaion created successfully. '.$renResult);


        } else {
            $request->session()->flash('alert-danger', 'Notificaion creation failed');
        }          

        
        return redirect()->route('notifications.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function show(Notification $notification)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function edit(Notification $notification)
    {        
        $notificationTypes = NotificationType::all();
        return view('admin.notifications.update')->with(['notification'=> $notification, 'notificationTypes'=>$notificationTypes]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notification $notification)
    {
        $niceNames = [
            'title' => 'Title',
            'type' => 'Type',
            'body' => 'Body',
            'img_name' => 'Image'
        ];
        $request->validate([
            'title' => 'required',
            'type' => 'required',
            'body' => 'required',
            'img_name' => 'image|mimes:jpg,jpeg,png,gif'
        ], [], $niceNames);
        //image
        $fileName = null;        
        
        if ($request->hasFile('img_name')) {
            $file = $request->file('img_name');
            $fileName = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
            $file->move('./uploads/notifications/', $fileName);

            $image_path = public_path().'/uploads/notifications/'.Notification::find($notification->id)->img_name;
            if(File::exists($image_path))    {
                File::delete($image_path);
            }
        }

        $notification->title = $request->get('title');
        $notification->type_id = $request->get('type');
        $notification->body = $request->get('body') ;
        if($fileName != null)
            $notification->img_name = $fileName;
        $notification->application_id =  session()->get('application')['id'];
        $notification->updated_by = Auth()->user()->id;

        if ($notification->save()) {
            $request->session()->flash('alert-success', 'Notification updated successfully');
        } else {
            $request->session()->flash('alert-danger', 'Notification update failed');
        }       
        return redirect()->route('notifications.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notification $notification)
    {
        if ($notification->delete()) {
            session()->flash('alert-success', 'Notification deleted successfully');
        } else {
            session()->flash('alert-danger', 'Notification delete failed');
        }
        return redirect()->route('notifications.index');
    }
}

resources/views/admin/notifications/create.blade.php
@extends('layouts.default') 
@section('css')
<link rel="stylesheet" href="{{ URL::asset('css/comboTreePlugin.css') }}" />
<style>
    .comboTreeDropDownContainer{
        z-index: 100;
    }
    .comboTreeArrowBtn{
        pointer-events: none !important;
        cursor: default !important;
    }

</style>
@endsection
    
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Notification</a>
            </li>
            <li class="active">Create new</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Create new notification
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))
                
                      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                      @endif
                    @endforeach
                </div>

                <form  enctype="multipart/form-data" class="form-horizontal" role="form"  method="post" action="/notifications">

                    @csrf
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('title') ? 'has-error' : '' }}">
                            <input type="text" class="form-control" id="form-field-1" value="{{ old('title') }}" name="title" placeholder="Title"  autocomplete='off' />
                            @if ($errors->has('title'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('title') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Select Type <span class="red">*</span> </label>

                        <div class="col-sm-6 {{ $errors->has('type') ? 'has-error' : '' }} ">
                            <select class="form-control" id="form-field-select-1" name="type">
                                <option value="">Select an option</option>
                                @foreach ($notificationTypes as $notificationType)
                                    <option value="{{$notificationType->id}}">{{$notificationType->name}}</option>
                                @endforeach
                            </select>
                           
                            @if ($errors->has('type'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('type') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Body <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('body') ? 'has-error' : '' }}">
                            <textarea rows="3" cols="60" name="body">{{ old('body') }}</textarea>                            
                            @if ($errors->has('body'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('body') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Add image </label>
                        <div class="col-sm-6 {{ $errors->has('img_name') ? 'has-error' : '' }}">
                            <input type="file" name="img_name" class="" id="id-input-file-2"  />
                            @if ($errors->has('img_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline "> {{ $errors->first('img_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                        
                    </div>

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit" onclick="if(confirm('Are you sure?')){}else{event.preventDefault();}">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Create
                            </button>
                            <a href="{{ URL::to('/notifications') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script src="{{ URL::asset('js/comboTreePlugin.js') }}"></script>
<script type="text/javascript">

    
    $( document ).ready(function() {
        
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #notificationsMenuId").addClass("active");

        $('#id-input-file-2').ace_file_input({
            no_file:'No File ...',
            btn_choose:'Choose',
            btn_change:'Change',
            droppable:false,
            onchange:null,
            thumbnail:false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });


    });
</script>
@endsection

resources/views/admin/notifications/index.blade.php
@extends('layouts.default') 
@section('css')

@endsection
 
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Notifications</a>
            </li>
            <li class="active">List view</li>
        </ul>
        <!-- /.breadcrumb -->
    </div>

    <div class="page-content">


        <div class="row">
            <div class="col-xs-12">

                <div class="row">
                    <div class="col-xs-12">
                        <h3 class="header smaller lighter blue">Notification List</h3>


                        {{--
                        <div class="clearfix">
                            <div class="pull-right tableTools-container"></div>
                        </div> --}}
                        <div class="flash-message">
                            @foreach (['danger', 'warning', 'success', 'info'] as $msg) 
                                @if(Session::has('alert-' . $msg))
                                    <p class="alert alert-{{ $msg }}">
                                        {{ Session::get('alert-' . $msg) }}
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    </p>
                                @endif 
                            @endforeach
                        </div>

                        <div class="table-header">
                            Notificatons {{--
                            <div class="row">
                                <div class="col-6">
                                    Results for "Latest Registered Domains"
                                </div>
                                <div class="col-6">

                                </div>
                            </div> --}}
                            <a href="{{ URL::to('/notifications/create') }}" class="btn btn-success pull-right">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Create
                            </a>

                        </div>
                        <div>
                        <table id="dynamic-table" class=" table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Title </th>
                                    <th>Type</th>
                                    <th>Body</th>
                                    <th>Image</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($notifications as $notification)
                                    <tr>
                                        <td>{{$notification->title}}</td>
                                        <td>{{$notification->type_name}}</td>
                                        <td>{{$notification->body}}</td>
                                        <td>
                                            @if( isset($notification->img_name ))
                                                <img alt="" height="20px" width="20px" src="uploads/notifications/{{$notification->img_name}}"/>
                                            @endif
                                        </td>
                                        <td>{{ \Carbon\Carbon::parse($notification->created_at)->format('d-m-Y')}}</td>
                                        <td>
                                            <div> 
                                                {{-- <a class="green" href="{{URL::to('/notifications/'.$notification->id.'/edit') }}">
                                                    <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                </a>                                     --}}

                                                <a class="red" href="javascript:void(0)"  onclick="event.preventDefault();
                                                         if(confirm('Are you sure?')){document.getElementById('delete-form_{{$notification->id}}').submit();}">
                                                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                </a>
                                                <form id="delete-form_{{$notification->id}}" action="{{ route('notifications.destroy', $notification->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                    </div>
                </div>
                <!-- PAGE CONTENT ENDS -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js') 

<script src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('js/jquery.dataTables.bootstrap.min.js') }}"></script>

<script type="text/javascript">
    
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #notificationsMenuId").addClass("active");

        $('#dynamic-table').DataTable({
            "ordering": false
        });

     });

</script>
@endsection

resources/views/admin/notifications/update.blade.php
@extends('layouts.default') 
@section('css')
<link rel="stylesheet" href="{{ URL::asset('css/comboTreePlugin.css') }}" />
<style>
    .comboTreeDropDownContainer{
        z-index: 100;
    }
    .comboTreeArrowBtn{
        pointer-events: none !important;
        cursor: default !important;
    }

</style>
@endsection
    
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Notification</a>
            </li>
            <li class="active">Update</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Update notification
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))
                
                      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                      @endif
                    @endforeach
                </div>

                <form  enctype="multipart/form-data" class="form-horizontal" role="form"  method="post" action="/notifications/{{$notification->id}}">

                    @method('PATCH')
                    @csrf
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('title') ? 'has-error' : '' }}">
                            <input type="text" class="form-control" id="form-field-1" value="{{ $notification->title}}" name="title" placeholder="Title"  autocomplete='off' />
                            @if ($errors->has('title'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('title') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Select Type <span class="red">*</span> </label>

                        <div class="col-sm-6 {{ $errors->has('type') ? 'has-error' : '' }} ">
                            <select class="form-control" id="form-field-select-1" name="type">
                                <option value="">Select an option</option>
                                @foreach ($notificationTypes as $notificationType)
                                    <option value="{{ $notificationType->id}}" {{$notification->type_id == $notificationType->id? 'selected': ''}}>{{ $notificationType->name}}</option>
                                @endforeach
                            </select>
                           
                            @if ($errors->has('type'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('type') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('body') ? 'has-error' : '' }}">
                            <textarea rows="3" cols="60" name="body">{{ $notification->body }}</textarea>                            
                            @if ($errors->has('body'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('body') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Add image </label>
                        <div class="col-sm-6 {{ $errors->has('img_name') ? 'has-error' : '' }}">
                            <input type="file" name="img_name" class="" id="id-input-file-2"  />
                            @if ($errors->has('img_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline "> {{ $errors->first('img_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                        
                    </div>

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Update
                            </button>
                            <a href="{{ URL::to('/notifications') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script src="{{ URL::asset('js/comboTreePlugin.js') }}"></script>
<script type="text/javascript">

    
    $( document ).ready(function() {
        
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #notificationsMenuId").addClass("active");

        $('#id-input-file-2').ace_file_input({
            no_file:'No File ...',
            btn_choose:'Choose',
            btn_change:'Change',
            droppable:false,
            onchange:null,
            thumbnail:false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });


    });
</script>
@endsection