routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){

    Auth::routes();
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/redirect_to_sa_panel', 'DashboardController@redirectToSaPanel');

    // Route::get('/applications', function () {
    //     return view('pages.applications.index');
    // });

    // Route::get('/applications/create', function () {
    //     return view('pages.applications.create');
    // });

    Route::resource('applications', 'ApplicationController');
    Route::get('/application_detail/{id}', 'ApplicationController@applicationDetail');

    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
    Route::post('/image-file-delete', 'PostController@imageFileDelete')->name('imageFileDelete');

    Route::resource('notifications', 'NotificationController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/notification-type', 'SettingsController@notificationTypeStore')->name('notificationTypeCreate');
    Route::put('/notification-type', 'SettingsController@notificationTypeUpdate')->name('notificationTypeUpdate');
    Route::delete('/notification-type/{id}', 'SettingsController@notificationTypeDelete')->name('notificationTypeDelete');

    Route::post('/server-key', 'SettingsController@serverKey')->name('serverKey');

    Route::get('/firebase','FirebaseController@index');
    // Route::resources([
    //     'applications' => 'ApplicationController'
    // ]);
});
  

app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB; 

class Application extends Model
{
    //

    public $timestamps = true;

   public function user()
   {
      return $this->belongsTo('App\User', 'user_id');
   }
   public static function getApplicationList()
   {
      return DB::table('applications')
         // ->join('users', 'users.id', '=', 'applications.user_id')
         ->select("applications.*", "applications.name as app_name")
         ->orderBy('applications.id', 'desc')
         ->get();
   }
}

app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Application;
use App\User;
use DB;
use Auth;

class ApplicationController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('superAdmin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $applications = Application::orderBy('id', 'desc')->get();
        // return view('superAdmin.applications.index')->with('applications', $applications);
        $applications = Application::getApplicationList();
        return view('superAdmin.applications.index')->with('applications', $applications);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$users = User::where('name', '!=', 'Super Admin')->orderBy('name', 'ASC')->get();
        $users = User::getAdminList();
        return view('superAdmin.applications.create')->with('users', $users);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $niceNames = [
        //     'name' => 'Application Name',
        //     'user_id' => 'Assign to'
        // ];
        // $validator = Validator::make($request->all(), [
        //     'name' => 'required|max:50',
        //     'user_id' => 'required'
        // ],[],$niceNames);

        // if ($validator->fails()) {
        //     return redirect('applications/create') //change this to your desired url
        //         ->withErrors($validator)
        //         ->withInput();
        // }

        $niceNames = [
            'name' => 'Application Name'
            //'user_id' => 'Assign to'
        ];
        $request->validate([
            'name' => 'required|max:50'
            //'user_id' => 'required'
        ], [], $niceNames);

        $application = new Application();
        $application->name = $request->get('name');
        $application->user_id = 2; //$request->get('user_id');

        if ($application->save()) {
            $request->session()->flash('alert-success', 'Application created successfully');
        } else {
            $request->session()->flash('alert-danger', 'Application creation failed');
        }
        //return redirect()->back()->withInput();
        return redirect()->route('applications.create');
        
        //return view('superAdmin.applications.create');
        //return redirect()->route('applications.create');
        //return redirect("applications/create");
        //return redirect()->action('ApplicationController@index');
        //return  $this->index();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $application = Application::findOrFail($id);
        $users = User::getAdminList();
        return view('superAdmin.applications.update')->with(['application' => $application, 'users' => $users]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd( $request->all());
        $niceNames = [
            'name' => 'Application Name'
            //'user_id' => 'Assign to'
        ];
        $request->validate([
            'name' => 'required|max:50'
            //'user_id' => 'required'
        ], [], $niceNames);

        $application = Application::find($id);
        $application->name = $request->get('name');
        $application->user_id = 2; ///$request->get('user_id');

        if ($application->save()) {
            $request->session()->flash('alert-success', 'Application updated successfully');
        } else {
            $request->session()->flash('alert-danger', 'Application update failed');
        }
        //return redirect()->back()->withInput();
        return redirect()->route('applications.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       //dd( $id);
        $application = Application::find($id);
        //dd( $application);
       //$res = Application::where('id',$id)->delete();
        if ($application->delete()) {
            session()->flash('alert-success', 'Application deleted successfully');
        } else {
            session()->flash('alert-danger', 'Application delete failed');
        }
        return redirect()->route('applications.index');
    }

    public function applicationDetail($id)
    {
        $application = Application::find($id);

        session()->put('application', [
            'id' => $application->id,
            'name' => $application->name
        ]);
        return redirect()->action('DashboardController@index');
    }



}

resources/views/superAdmin/applications/create.blade.php
@extends('layouts.default') 
@section('css')

@endsection
 
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Application</a>
            </li>
            <li class="active">Create new</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Create new application
                <!-- <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Common form elements and layouts
                </small> -->
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                
                {{--  @if (count($errors) > 0)
                    <div class = "alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  --}}
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))
                
                      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                      @endif
                    @endforeach
                </div>
                <form class="form-horizontal" role="form"  method="post" action="/applications">

                    <input name="_token" type="hidden" value="{{ csrf_token() }}"/>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Application Name <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('name') ? 'has-error' : '' }}">
                            <input type="text" id="form-field-1" value="{{ old('name') }}" name="name" placeholder="Application Name" class="form-control" />
                            @if ($errors->has('name'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                    {{-- <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Assign to <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('user_id') ? 'has-error' : '' }} ">
                            <select class="form-control" id="form-field-select-1" name="user_id">
                                <option value="">Select an option</option>
                                
                                @foreach($users as $key => $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach

                            </select>
                            @if ($errors->has('user_id'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('user_id') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>

                    </div> --}}

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Create
                            </button>
                            <a href="{{ URL::to('/applications') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script type="text/javascript">
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #applciationsMenuId").addClass("active");
    });
</script>
@endsection

resources/views/superAdmin/applications/index.blade.php
@extends('layouts.default')

@section('css')
  
@endsection

@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Application</a>
            </li>
            <li class="active">List view</li>
        </ul><!-- /.breadcrumb -->
    </div>

    <div class="page-content">
        

        <div class="row">
            <div class="col-xs-12">
                
                <div class="row">
                    <div class="col-xs-12">
                         <h3 class="header smaller lighter blue">Applicatons List</h3>
                         

                        {{--  <div class="clearfix">
                            <div class="pull-right tableTools-container"></div>
                        </div>   --}}
                        <div class="flash-message">
                            @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                                @if(Session::has('alert-' . $msg))                
                                <p class="alert alert-{{ $msg }}">
                                    {{ Session::get('alert-' . $msg) }} 
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                </p>
                                @endif
                            @endforeach
                        </div>
                            
                        <div class="table-header">
                                Results for "Latest Registered Domains"
                            {{--  <div class="row">
                                <div class="col-6">
                                        Results for "Latest Registered Domains"
                                </div>
                                <div class="col-6">
                                        
                                </div>
                            </div>  --}}
                            <a href="{{ URL::to('/applications/create') }}" class="btn btn-success pull-right" >
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Create
                            </a>
                            
                        </div>

                        <!-- div.table-responsive -->

                        <!-- div.dataTables_borderWrap -->
                        <div>
                            <table id="dynamic-table" class=" table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        
                                        <th>Name</th>
                                        {{--  <th>Assign To</th>  --}}
                                        <th>Created At</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    
                                    @foreach($applications as $key => $application)
                                        <tr>    
                                            <td>                                                
                                                <a class="blue" href="{{ URL::to('/application_detail/'.$application->id) }}">
                                                    {{$application->name}}
                                                </a>
                                            </td>
                                            {{--  <td>{{$application->user_name}}</td>  --}}
                                            <td>{{$application->created_at}}</td>
                                            <td >
                                                <div > 
                                                    <a class="green" href="{{URL::to('/applications/'.$application->id.'/edit') }}">
                                                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                    </a>                                    
                                                    &nbsp;&nbsp;
                                                    <a class="red" href="javascript:void(0)"  onclick="event.preventDefault();
                                                             if(confirm('Are you sure?')){document.getElementById('delete-form_{{$application->id}}').submit();}">
                                                        <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                    </a>
                                                    <form id="delete-form_{{$application->id}}" action="{{ route('applications.destroy', $application->id)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>
                                                </div>
                                            </td>                 
                                        </tr>
                                    @endforeach

                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

               

                <!-- PAGE CONTENT ENDS -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.page-content -->
</div>

@endsection

@section('js')

<script src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('js/jquery.dataTables.bootstrap.min.js') }}"></script>

<script type="text/javascript">
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #applciationsMenuId").addClass("active");

        $('#dynamic-table').DataTable({
            "ordering": false
        });
     });

</script>

@endsection

resources/views/superAdmin/applications/update.blade.php
@extends('layouts.default') 
@section('css')

@endsection
 
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Application</a>
            </li>
            <li class="active">Update Application</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Update application
                <!-- <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Common form elements and layouts
                </small> -->
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                
                {{--  @if (count($errors) > 0)
                    <div class = "alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  --}}
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))                
                        <p class="alert alert-{{ $msg }}">
                            {{ Session::get('alert-' . $msg) }} 
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        </p>
                      @endif
                    @endforeach
                </div>
                <form class="form-horizontal" role="form"  method="post" action="/applications/{{$application->id}}">
                    @method('PATCH')
                    @csrf

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Application Name <span class="red">*</span></label>

                        <div class="col-sm-9 {{ $errors->has('name') ? 'has-error' : '' }}">
                            <input type="text" id="form-field-1" value="{{ $application->name }}" name="name" placeholder="Application Name" class="col-xs-10 col-sm-5" />
                            @if ($errors->has('name'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('name') }} </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Assign to <span class="red">*</span></label>

                        <div class="col-sm-9 {{ $errors->has('user_id') ? 'has-error' : '' }} ">
                            <select class=" col-xs-10 col-sm-5" id="form-field-select-1" name="user_id">
                                <option value="">Select an option</option>
                                
                                @foreach($users as $key => $user)
                                    @if($user->id == $application->user_id)
                                        <option value="{{$user->id}}" selected >{{$user->name}}</option>
                                    @else
                                        <option value="{{$user->id}}"  >{{$user->name}}</option>
                                    @endif
                                @endforeach

                            </select>
                            @if ($errors->has('user_id'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('user_id') }} </div>
                            @endif
                        </div>

                    </div>

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Update
                            </button>
                            <a href="{{ URL::to('/applications') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script type="text/javascript">
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #applciationsMenuId").addClass("active");
    });
</script>
@endsection