routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){

    Auth::routes();
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/redirect_to_sa_panel', 'DashboardController@redirectToSaPanel');

    // Route::get('/applications', function () {
    //     return view('pages.applications.index');
    // });

    // Route::get('/applications/create', function () {
    //     return view('pages.applications.create');
    // });

    Route::resource('applications', 'ApplicationController');
    Route::get('/application_detail/{id}', 'ApplicationController@applicationDetail');

    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
    Route::post('/image-file-delete', 'PostController@imageFileDelete')->name('imageFileDelete');

    Route::resource('notifications', 'NotificationController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/notification-type', 'SettingsController@notificationTypeStore')->name('notificationTypeCreate');
    Route::put('/notification-type', 'SettingsController@notificationTypeUpdate')->name('notificationTypeUpdate');
    Route::delete('/notification-type/{id}', 'SettingsController@notificationTypeDelete')->name('notificationTypeDelete');

    Route::post('/server-key', 'SettingsController@serverKey')->name('serverKey');

    Route::get('/firebase','FirebaseController@index');
    // Route::resources([
    //     'applications' => 'ApplicationController'
    // ]);
});
  

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    public $timestamps = true;
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use App\Http\Controllers\API\Controller as Controller;
use App\Category;
use App\Post;
use Validator;
use App\PostCategories;
use App\PostImages;
use App\AdditionalFields;
use Mockery\Undefined;
use DB;


class PostController extends Controller
{

    
    /*
    * 
    * localhost:8000/api/post-list
    * Mthoed: POST    
    * Body:{
                "app_id": 1, (Mandatory fields)
                "post_id": 1 (optional fiels) -get specific post
            }
    * 
    */
    public function postList(Request $request){

        $body  = $request->all();
        $posts =  Post::where('application_id',$body['app_id']);
                    if(isset($body['post_id']))  
                        $posts->where('posts.id', $body['post_id'])  ;
        $posts =    $posts->orderBy('id','DESC')->get();

        $postImages = PostImages::select('post_images.*')
                    ->join('posts', 'posts.id', '=', 'post_images.post_id')
                    ->where('posts.application_id', $body['app_id']);
                        if(isset($body['post_id']))  
                            $postImages->where('post_images.post_id', $body['post_id'])  ;
        $postImages = $postImages->get();

        $additionalFields = AdditionalFields::select('additional_fields.*')
                ->join('posts', 'posts.id', '=', 'additional_fields.post_id')
                ->where('posts.application_id', $body['app_id']);
                if(isset($body['post_id']))  
                    $additionalFields->where('additional_fields.post_id', $body['post_id'])  ;
        $additionalFields = $additionalFields->get();

        $postCategories = PostCategories::select('categories.*','post_categories.post_id as post_id')
                ->join('posts', 'posts.id', '=', 'post_categories.post_id')
                ->join('categories', 'categories.id', '=', 'post_categories.category_id')
                ->where('posts.application_id', $body['app_id']);
                if(isset($body['post_id']))  
                    $postCategories->where('post_categories.post_id', $body['post_id'])  ;
        $postCategories = $postCategories->get();
               
        $formatedPost = $this->postListFormate($posts, $postImages, $additionalFields, $postCategories);

        if (is_null($posts)) {
            return $this->sendError('Category not found.');
        }

        return $this->sendResponse($formatedPost, 'Post retrieved successfully.');
    }


    /*
    * 
    * localhost:8000/api/post-list-by-category-id
    * Mthoed: POST    
    * Body:{
                "app_id": 1, (Mandatory fields)
                "category_id": 1 (Mandatory fields)
            }
    * 
    */
    public function postListByCategoryId(Request $request){

        $body  = $request->all();

        $postList = PostCategories::select('posts.*')
                ->join('posts', 'posts.id', '=', 'post_categories.post_id')
                ->where('posts.application_id', $body['app_id'])
                ->where('post_categories.category_id', $body['category_id'])  
                ->get();

               
        $postIdList = [];
        for($i = 0; $i < count($postList); $i++){
            $postIdList[$i] = $postList[$i]['id'];
        }




        $posts =  Post::where('application_id',$body['app_id']) 
                    ->whereIn('id', $postIdList)
                    ->orderBy('id','DESC')->get();

                    
        $postImages = PostImages::select('post_images.*')
                    ->join('posts', 'posts.id', '=', 'post_images.post_id')
                    ->where('posts.application_id', $body['app_id'])
                    ->whereIn('posts.id', $postIdList)
                    ->get();

        $additionalFields = AdditionalFields::select('additional_fields.*')
                ->join('posts', 'posts.id', '=', 'additional_fields.post_id')
                ->where('posts.application_id', $body['app_id'])
                ->whereIn('posts.id', $postIdList)
                ->get();

        $postCategories = PostCategories::select('categories.*','post_categories.post_id as post_id')
                ->join('posts', 'posts.id', '=', 'post_categories.post_id')
                ->join('categories', 'categories.id', '=', 'post_categories.category_id')
                ->where('posts.application_id', $body['app_id'])
                ->whereIn('posts.id', $postIdList)
                ->get();
               
        $formatedPost = $this->postListFormate($posts, $postImages, $additionalFields, $postCategories);

        if (is_null($posts)) {
            return $this->sendError('Category not found.');
        }

        return $this->sendResponse($formatedPost, 'Post retrieved successfully.');
    }



     /*
    * 
    * localhost:8000/api/post-list-by-search-key
    * Mthoed: POST    
    * Body:{
                "app_id": 1, (Mandatory fields)
                "search_key": 'ds' (Mandatory fields)
            }
    * 
    */
    public function postListBySearchKey(Request $request){

        $body  = $request->all();

        $searchKeyArr = explode(" ", $body['search_key']);
        $searchKey = "";
        for($i=0; $i<count($searchKeyArr); $i++){

            if($searchKeyArr[$i] != ""){
                if($searchKey!= ""){
                    $searchKey .= "%";
                }
                $searchKey .=$searchKeyArr[$i];
            }

        }

        //dd($searchKey);
        $query = " SELECT * FROM posts ".
                    " WHERE application_id = ".$body['app_id'] .
                " AND ( title LIKE '%".$searchKey."%' OR  'desc' LIKE '%".$searchKey."%' ) ";
                //dd($query);

        $postList = DB::select($query);
        $postIdList = [];
        for($i = 0; $i < count($postList); $i++){
            $postIdList[$i] = $postList[$i]->id;
        }

        $posts =  Post::where('application_id',$body['app_id']) 
                ->whereIn('id', $postIdList)
                ->orderBy('id','DESC')->get();

        $postImages = PostImages::select('post_images.*')
                ->join('posts', 'posts.id', '=', 'post_images.post_id')
                ->where('posts.application_id', $body['app_id'])
                ->whereIn('posts.id', $postIdList)
                ->get();

        $additionalFields = AdditionalFields::select('additional_fields.*')
                ->join('posts', 'posts.id', '=', 'additional_fields.post_id')
                ->where('posts.application_id', $body['app_id'])
                ->whereIn('posts.id', $postIdList)
                ->get();

        $postCategories = PostCategories::select('categories.*','post_categories.post_id as post_id')
                ->join('posts', 'posts.id', '=', 'post_categories.post_id')
                ->join('categories', 'categories.id', '=', 'post_categories.category_id')
                ->where('posts.application_id', $body['app_id'])
                ->whereIn('posts.id', $postIdList)
                ->get();
        
        $formatedPost = $this->postListFormate($posts, $postImages, $additionalFields, $postCategories);

       

        if (is_null($formatedPost)) {
            return $this->sendError('Category not found.');
        }


        return $this->sendResponse($formatedPost, 'Post retrieved successfully.');

    }





    private function postListFormate($posts, $postImages, $additionalFields, $postCategories){

        $formatedPost = [];

        for($i = 0; $i < count($posts) ; $i++){

            $formatedPost[$i]["id"] =       $posts[$i]["id"];
            $formatedPost[$i]["title"] =    $posts[$i]["title"];
            $formatedPost[$i]["desc"] =     $posts[$i]["desc"];
            $formatedPost[$i]["phone"] =    is_null($posts[$i]["phone"])?"":$posts[$i]["phone"];
            $formatedPost[$i]["email"] =   is_null($posts[$i]["email"])?"":$posts[$i]["email"];
            $formatedPost[$i]["lati"] =    is_null($posts[$i]["lati"])?"":$posts[$i]["lati"]; 
            $formatedPost[$i]["long"] =     is_null($posts[$i]["long"])?"":$posts[$i]["long"];
            $formatedPost[$i]["is_featured"] =  is_null($posts[$i]["is_featured"])?"":$posts[$i]["is_featured"];
            $formatedPost[$i]["post_type"] =  is_null($posts[$i]["post_type"])?"":$posts[$i]["post_type"];
            $formatedPost[$i]["media_link"] = is_null($posts[$i]["media_link"])?"":$posts[$i]["media_link"]; 
            $formatedPost[$i]["is_public"] =  is_null($posts[$i]["is_public"])?"":$posts[$i]["is_public"];
            $formatedPost[$i]["is_published"] =  is_null($posts[$i]["is_published"])?"":$posts[$i]["is_published"];
            $formatedPost[$i]["alive_date"] =  is_null($posts[$i]["alive_date"])?"":$posts[$i]["alive_date"];
            $formatedPost[$i]["application_id"] = is_null($posts[$i]["application_id"])?"":$posts[$i]["application_id"];
            $formatedPost[$i]["modified_date"] =  isset($posts[$i]["updated_at"])&&!empty($posts[$i]["updated_at"]) ? Carbon::parse($posts[$i]["created_at"])->format('d-m-Y') : Carbon::parse($posts[$i]["updated_at"])->format('d-m-Y') ;

            $formatedPost[$i]["images"] = [];
            $formatedPost[$i]["category_id"] = [];
            $formatedPost[$i]["attachments"] = [];
            $formatedPost[$i]["additionals"] =[];

            for($j = 0; $j < count($postImages) ; $j++){

                if($postImages[$j]['post_id'] == $posts[$i]["id"]){

                    $tempPI = [];
                    $tempPI["id"] =  $postImages[$j]['id'];
                    $tempPI["img_name"] =  $postImages[$j]['img_name'];
                    $tempPI["img_path"] =  $postImages[$j]['img_path'];
                    $tempPI["org_name"] =  $postImages[$j]['org_name'];
                    $tempPI["type"] =  $postImages[$j]['type'];
                    $tempPI["ext"] =  $postImages[$j]['ext'];

resources/views/admin/posts/index.blade.php
@extends('layouts.default')

@section('css')
  
@endsection

@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">All Post</a>
            </li>
            <li class="active">List view</li>
        </ul><!-- /.breadcrumb -->
    </div>

    <div class="page-content">
        

        <div class="row">
            <div class="col-xs-12">
                
                <div class="row">
                    <div class="col-xs-12">
                         <h3 class="header smaller lighter blue">All Post</h3>
                         

                        {{--  <div class="clearfix">
                            <div class="pull-right tableTools-container"></div>
                        </div>   --}}
                        <div class="flash-message">
                            @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                                @if(Session::has('alert-' . $msg))                
                                <p class="alert alert-{{ $msg }}">
                                    {{ Session::get('alert-' . $msg) }} 
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                </p>
                                @endif
                            @endforeach
                        </div>
                            
                        <div class="table-header">
                            Post List
                            <a href="{{ URL::to('/posts/create') }}" class="btn btn-success pull-right" >
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Create
                            </a>
                            
                        </div>

                        <!-- div.table-responsive -->

                        <!-- div.dataTables_borderWrap -->
                        <div>
                            <table id="dynamic-table" class=" table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Category</th>
                                        {{--  <th>Phone</th>
                                        <th>Email</th>
                                        <th>Latitude</th>
                                        <th>longitude</th>  --}}
                                        <th>Featured</th>
                                        {{--  <th>Image</th>  --}}
                                        {{--  <th>Media</th>  --}}
                                        <th>Public </th>
                                        <th>Published</th>
                                        <th>Alive Date</th>
                                        <th>Created At</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    
                                    @foreach($posts as $key => $post)
                                        <tr>    
                                            <td> <img alt="" height="30px" width="30px" src="{{$post->img_path}}"/></td>
                                            <td>                                                
                                                <a class="blue" href="{{ URL::to('/posts/'.$post->id) }}">{{$post->title}}</a>  
                                                {{--  {{$post->title}}  --}}
                                            </td>
                                            <td>{{$post->category_name}}</td>
                                            {{--  <td>{{$post->phone}}</td>
                                            <td>{{$post->email}}</td>
                                            <td>{{$post->lati}}</td>
                                            <td>{{$post->long}}</td>  --}}
                                            <td>
                                                @if ($post->is_featured == 1)
                                                    <i class="ace-icon fa fa-check bigger-130"></i>
                                                @endif                                                    
                                            </td>
                                            {{--  <td>
                                                <img alt="" height="20px" width="20px" src="uploads/posts/{{$post->img_name}}"/>
                                            </td>  --}}
                                            {{--  <td>{{$post->media_link}}</td>  --}}
                                            <td>
                                                @if ($post->is_public == 1)
                                                    <i class="ace-icon fa fa-check bigger-130"></i>
                                                @endif
                                            </td>
                                            <td>
                                                @if ($post->is_published == 1)
                                                    <i class="ace-icon fa fa-check bigger-130"></i>
                                                @endif
                                            </td>
                                            <td>{{ \Carbon\Carbon::parse($post->alive_date)->format('d-m-Y')}}</td>
                                            <td>{{ \Carbon\Carbon::parse($post->created_at)->format('d-m-Y')}}</td>
                                            <td >
                                                <div > 
                                                    <a class="green" href="{{URL::to('/posts/'.$post->id.'/edit') }}">
                                                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                    </a>   &nbsp;&nbsp;
    
                                                    <a class="red" href="javascript:void(0)"  onclick="event.preventDefault();
                                                             if(confirm('Are you sure?')){document.getElementById('delete-form_{{$post->id}}').submit();}">
                                                        <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                    </a>
                                                    <form id="delete-form_{{$post->id}}" action="{{ route('posts.destroy', $post->id)}}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>
                                                </div>
                                            </td>                 
                                        </tr>
                                    @endforeach

                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

               

                <!-- PAGE CONTENT ENDS -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.page-content -->
</div>

@endsection

@section('js')

<script src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('js/jquery.dataTables.bootstrap.min.js') }}"></script>

<script type="text/javascript">
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #postsMenuId").addClass("active");

        $('#dynamic-table').DataTable({
            "ordering": false
        });
     });

</script>

@endsection