routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){

    Auth::routes();
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/redirect_to_sa_panel', 'DashboardController@redirectToSaPanel');

    // Route::get('/applications', function () {
    //     return view('pages.applications.index');
    // });

    // Route::get('/applications/create', function () {
    //     return view('pages.applications.create');
    // });

    Route::resource('applications', 'ApplicationController');
    Route::get('/application_detail/{id}', 'ApplicationController@applicationDetail');

    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
    Route::post('/image-file-delete', 'PostController@imageFileDelete')->name('imageFileDelete');

    Route::resource('notifications', 'NotificationController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/notification-type', 'SettingsController@notificationTypeStore')->name('notificationTypeCreate');
    Route::put('/notification-type', 'SettingsController@notificationTypeUpdate')->name('notificationTypeUpdate');
    Route::delete('/notification-type/{id}', 'SettingsController@notificationTypeDelete')->name('notificationTypeDelete');

    Route::post('/server-key', 'SettingsController@serverKey')->name('serverKey');

    Route::get('/firebase','FirebaseController@index');
    // Route::resources([
    //     'applications' => 'ApplicationController'
    // ]);
});
  

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    public $timestamps = true;
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use App\Http\Controllers\API\Controller as Controller;
use App\Library\Services\CategoryService;
use App\Category;
use Validator;


class CategoryController extends Controller
{

    //public $apiFmtCategories = [];

    // public function index()
    // {        
    //      $catagories = Category::all();
    //      return $this->sendResponse($catagories->toArray(), 'Categories retrieved successfully.');
    // }

    /*
    * 
    * localhost:8000/api/category-list
    * Mthoed: POST    
    * Body:{ "app_id": 1 }
    * 
    */
    public function categoryList(Request $request){

        $body  = $request->all();
        $categoryService = new CategoryService ();
        $categories = $categoryService->getStructuredCategories( $body['app_id'] );
        $categoriesFormated  = $this->categoryListFormat($categories);
        if (is_null($categories)) {
            return $this->sendError('Category not found.');
        }
        return $this->sendResponse($categoriesFormated, 'Category retrieved successfully.');
    }








    private function categoryListFormat($arr){

        $apiFmtCategories =[];

        for ($i = 0; $i < count($arr); $i++) {
            
                $obj = [
                        'id' => $arr[$i]['id'], 
                        'title' => $arr[$i]['name'], 
                        'image_url' => url('uploads/categories/'.$arr[$i]['img_name'] ),
                        'parent_id' => $arr[$i]['p_id'], 
                        'has_child' => isset($arr[$i]['subs']) ? true : false, 
                        'modified_date' => isset($arr[$i]["updated_at"])&&!empty($arr[$i]["updated_at"]) ? Carbon::parse($arr[$i]["created_at"])->format('d-m-Y') : Carbon::parse($arr[$i]["updated_at"])->format('d-m-Y') , 
                        'sub' => []
                    ];            

                array_push($apiFmtCategories,  $obj);
            

            if (isset($arr[$i]['subs'])) {
                $apiFmtCategories[$i]['sub'] =  $this->categoryListFormat($arr[$i]['subs']);                
            }

        }
        return $apiFmtCategories;
    }



}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Library\Services\CategoryService;
use App\Category;
use DB;
use File;

class CategoryController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CategoryService $categoryService)
    {
        $categories = $categoryService->getStructuredCategories(session()->get('application')['id']);
        $fmtCategoriesForTable = $categoryService->categoriesFormatForTable($categories,'','');
        return view('admin.categories.index')->with('categories', $fmtCategoriesForTable);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(CategoryService $categoryService)
    {
        $categories = $categoryService->getStructuredCategories(session()->get('application')['id']);
        return view('admin.categories.create')->with('categories', $categories);;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $niceNames = [
            'title' => 'Title',
            'p_id' => 'Select root',
            'img_name' => 'Add image'
        ];
        $request->validate([
            'title' => 'required|max:50',
            'img_name' => 'required|image|mimes:jpg,jpeg,png,gif'
        ], [], $niceNames);

        $category = Category::Where('name',$request->get('title'))->get();
        if(count($category) == 0 ){
            $fileName = null;
            if ($request->hasFile('img_name')) {
                $file = $request->file('img_name');
                $fileName = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
                $file->move('./uploads/categories/', $fileName);
            }
    
            $category = new Category();
            $category->name = $request->get('title');
            $category->img_name = $fileName;
            $category->application_id = session()->get('application')['id'];
            $category->created_by = Auth()->user()->id;
    
            $catData = Category::Where('name', $request->get('p_name'))->first();
            if ($catData)
                $category->p_id = $catData->id;
            else
                $category->p_id = 0;
    
            if ($category->save()) {
                session()->flash('alert-success', 'Category created successfully');
            } else {
                session()->flash('alert-danger', 'Category creation failed');
            }

        }else{
            session()->flash('alert-danger', 'Category Title already exist.');
        }
        return redirect()->route('categories.create');
                
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        dd($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category, CategoryService $categoryService)
    {
        //dd($$categoryArr);
        $categories = $categoryService->getStructuredCategories(session()->get('application')['id']);
        $categoryArr = Category::where('id', $category->p_id)->get();
        $category->p_name = count($categoryArr)>0 ? $categoryArr[0]->name : '';

        return view('admin.categories.update')->with(['category' => $category,'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // print_r($category);
        // dd($request->all());
        $niceNames = [
            'title' => 'Title',
            'p_id' => 'Select root',
            'img_name' => 'Add image'
        ];
        $request->validate([
            'title' => 'required|max:50',
            'img_name' => 'image|mimes:jpg,jpeg,png,gif'
        ], [], $niceNames);

        $fileName = null;
        if ($request->hasFile('img_name')) {
            $file = $request->file('img_name');
            $fileName = md5($file->getClientOriginalName() . time()) . "." . $file->getClientOriginalExtension();
            $file->move('./uploads/categories/', $fileName);

            //delete the file folder public folder
            $image_path = public_path().'/uploads/categories/'.Category::find($category->id)->img_name;
            if(File::exists($image_path))    {
                File::delete($image_path);
            }
        }

        $category =  Category::find($category->id);
        $category->name = $request->get('title');
        if($fileName != null)
            $category->img_name = $fileName;

        $category->application_id = session()->get('application')['id'];
        $category->updated_by = Auth()->user()->id;

        $catData = Category::Where('name', $request->get('p_name'))->first();
        if ($catData)
            $category->p_id = $catData->id;
        else
            $category->p_id = 0;

        if ($category->save()) {
            session()->flash('alert-success', 'Category updated successfully');
        } else {
            session()->flash('alert-danger', 'Category update failed');
        }
        return redirect()->route('categories.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //dd($category);
        //$category = Category::find($category->id);
        if ($category->delete()) {
            session()->flash('alert-success', 'Category deleted successfully');
        } else {
            session()->flash('alert-danger', 'Category delete failed');
        }
        return redirect()->route('categories.index');
    }





    
}

resources/views/admin/categories/create.blade.php
@extends('layouts.default') 
@section('css')
<link rel="stylesheet" href="{{ URL::asset('css/comboTreePlugin.css') }}" />
<style>
    .comboTreeDropDownContainer{
        z-index: 100;
    }
    .comboTreeArrowBtn{
        pointer-events: none !important;
        cursor: default !important;
    }

</style>
@endsection
    
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Category</a>
            </li>
            <li class="active">Create new</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Create new category
                <!-- <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Common form elements and layouts
                </small> -->
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                
                {{--  @if (count($errors) > 0)
                    <div class = "alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  --}}
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))
                
                      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                      @endif
                    @endforeach
                </div>

                <form  enctype="multipart/form-data" class="form-horizontal" role="form"  method="post" action="/categories">

                    @csrf
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('title') ? 'has-error' : '' }}">
                            <input type="text" class="form-control" id="form-field-1" value="{{ old('title') }}" name="title" placeholder="Title"  autocomplete='off' />
                            @if ($errors->has('title'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('title') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Select root </label>

                        <div class="col-sm-6 {{ $errors->has('p_name') ? 'has-error' : '' }} ">
                            {{--  <select class=" col-xs-10 col-sm-5" id="form-field-select-1" name="p_id">
                                <option value="0">Select an option</option>
                                
                                @foreach($categories as $key => $categorie)
                                    <option value="{{$categorie->id}}">{{$categorie->name}}</option>
                                @endforeach

                            </select>  --}}
                            <input type="text" name="p_name"  class="form-control" id="categoryid" placeholder="Select an option" autocomplete='off'/>
                            @if ($errors->has('p_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('p_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Add image <span class="red">*</span></label>
                        <div class="col-sm-6 {{ $errors->has('img_name') ? 'has-error' : '' }}">
                            <input type="file" name="img_name" class="" id="id-input-file-2"  />
                            @if ($errors->has('img_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline "> {{ $errors->first('img_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                        
                    </div>

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Create
                            </button>
                            <a href="{{ URL::to('/categories') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script src="{{ URL::asset('js/comboTreePlugin.js') }}"></script>
<script type="text/javascript">

    var catData =  {!! json_encode($categories) !!};

    $( document ).ready(function() {
        
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #categoriesMenuId").addClass("active");

        $('#id-input-file-2').ace_file_input({
            no_file:'No File ...',
            btn_choose:'Choose',
            btn_change:'Change',
            droppable:false,
            onchange:null,
            thumbnail:false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });


        $('#categoryid').comboTree({
			source : catData,
			isMultiple: false
		});
    });
</script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.default') 
@section('css')
<link rel="stylesheet" href="{{ URL::asset('css/jquery.treetable.css') }}" />
<link rel="stylesheet" href="{{ URL::asset('css/jquery.treetable.theme.default.css') }}" />
@endsection
 
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Category</a>
            </li>
            <li class="active">List view</li>
        </ul>
        <!-- /.breadcrumb -->
    </div>

    <div class="page-content">


        <div class="row">
            <div class="col-xs-12">

                <div class="row">
                    <div class="col-xs-12">
                        <h3 class="header smaller lighter blue">Categories</h3>


                        {{--
                        <div class="clearfix">
                            <div class="pull-right tableTools-container"></div>
                        </div> --}}
                        <div class="flash-message">
                            @foreach (['danger', 'warning', 'success', 'info'] as $msg) 
                                @if(Session::has('alert-' . $msg))
                                    <p class="alert alert-{{ $msg }}">
                                        {{ Session::get('alert-' . $msg) }}
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    </p>
                                @endif 
                            @endforeach
                        </div>

                        <div class="table-header">
                            Category List {{--
                            <div class="row">
                                <div class="col-6">
                                    Results for "Latest Registered Domains"
                                </div>
                                <div class="col-6">

                                </div>
                            </div> --}}
                            <a href="{{ URL::to('/categories/create') }}" class="btn btn-success pull-right">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Create
                            </a>

                        </div>

                        <table id="example-advanced">
                            <thead>
                                <tr>
                                    <th><b>Name</b></th>
                                    <th><b>Image</b></th>
                                    <th><b>Create at</b></th>
                                    <th><b>Action</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($categories as $category)
                                    <tr data-tt-id='{{ $category['child_id'] }}' 
                                        @if($category['parent_id'] !='')
                                            data-tt-parent-id='{{ $category['parent_id'] }}'
                                         @endif
                                         >
                                        <td><span class='file'>{{ $category['name'] }}</span></td>
                                        <td>
                                            <img alt="" height="20px" width="20px" src="uploads/categories/{{$category['img_name'] }}"/>

                                        </td>
                                        <td>{{$category['created_at']}}</td>
                                        <td> 
                                            <a class="green" href="{{URL::to('/categories/'.$category['id'].'/edit') }}">
                                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                                            </a>  
                                            &nbsp;&nbsp;
                                            <a class="red" href="javascript:void(0)"  onclick="event.preventDefault();
                                                        if(confirm('Are you sure?')){document.getElementById('delete-form_{{$category['id']}}').submit();}">
                                                <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                            </a>
                                            <form id="delete-form_{{$category['id']}}" action="{{ route('categories.destroy', $category['id']) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>


                    </div>
                </div>
                <!-- PAGE CONTENT ENDS -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js') {{--
<script src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('js/jquery.dataTables.bootstrap.min.js') }}"></script> --}}
<script src="{{ URL::asset('js/jquery.treetable.js') }}"></script>

<script type="text/javascript">
    $( document ).ready(function() {
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #categoriesMenuId").addClass("active");



        $("#example-advanced").treetable({ expandable: true });

        // Highlight selected row
        $("#example-advanced tbody").on("mousedown", "tr", function() {
            $(".selected").not(this).removeClass("selected");
            $(this).toggleClass("selected");
        });
     });

</script>
@endsection

resources/views/admin/categories/update.blade.php
@extends('layouts.default') 
@section('css')
<link rel="stylesheet" href="{{ URL::asset('css/comboTreePlugin.css') }}" />
<style>
    .comboTreeDropDownContainer{
        z-index: 100;
    }
    .comboTreeArrowBtn{
        pointer-events: none !important;
        cursor: default !important;
    }

</style>
@endsection
    
@section('content')

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
            </li>

            <li>
                <a href="#">Category</a>
            </li>
            <li class="active">Update</li>
        </ul>
        <!-- /.breadcrumb -->

    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Update category
                <!-- <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Common form elements and layouts
                </small> -->
            </h1>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                
                {{--  @if (count($errors) > 0)
                    <div class = "alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif  --}}
                <div class="flash-message">
                    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                      @if(Session::has('alert-' . $msg))
                
                      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                      @endif
                    @endforeach
                </div>

                <form  enctype="multipart/form-data" class="form-horizontal" role="form"  method="post" action="/categories/{{$category->id}}">
                    @method('PATCH')
                    @csrf
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title <span class="red">*</span></label>

                        <div class="col-sm-6 {{ $errors->has('title') ? 'has-error' : '' }}">
                            <input type="text" class="form-control" id="form-field-1" value="{{ $category->name }}" name="title" placeholder="Title"  />
                            @if ($errors->has('title'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('title') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>

                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Select root </label>

                        <div class="col-sm-6 {{ $errors->has('p_name') ? 'has-error' : '' }} ">
                            <input type="text" name="p_name" value="{{$category->p_name}}" class="form-control" id="categoryid" placeholder="Select an option" autocomplete='off'/>
                            @if ($errors->has('p_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline"> {{ $errors->first('p_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                    <div class="form-group ">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1-1"> Add image </label>
                        <div class="col-sm-6 {{ $errors->has('img_name') ? 'has-error' : '' }}">
                            <input type="file" name="img_name" class="" id="id-input-file-2"  />
                            @if ($errors->has('img_name'))
                                <div class="help-block col-xs-12 col-sm-reset inline "> {{ $errors->first('img_name') }} </div>
                            @endif
                        </div>
                        <div class="col-sm-3"></div>
                        
                    </div>

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9 no-padding-left">
                            <button class="btn btn-primary" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Update
                            </button>
                            <a href="{{ URL::to('/categories') }}" class="btn btn-danger" >
                                <i class="ace-icon fa fa-close bigger-110"></i>
                                Exit
                            </a>
                        </div>
                    </div>



                </form>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</div>
@endsection
 
@section('js')
<script src="{{ URL::asset('js/comboTreePlugin.js') }}"></script>
<script type="text/javascript">

    var catData =  {!! json_encode($categories) !!};

    $( document ).ready(function() {
        
        $(".custom-menu-item li").removeClass("active");
        $(".custom-menu-item #categoriesMenuId").addClass("active");

        $('#id-input-file-2').ace_file_input({
            no_file:'No File ...',
            btn_choose:'Choose',
            btn_change:'Change',
            droppable:false,
            onchange:null,
            thumbnail:false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });


        $('#categoryid').comboTree({
			source : catData,
			isMultiple: false
		});
    });
</script>
@endsection